-- Create ideas table to store saved ideas
CREATE TABLE IF NOT EXISTS ideas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  persona VARCHAR(500) NOT NULL,
  industry VARCHAR(500) NOT NULL,
  idea TEXT NOT NULL,
  is_used BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Create index for better query performance
CREATE INDEX IF NOT EXISTS idx_ideas_user_id ON ideas(user_id);
CREATE INDEX IF NOT EXISTS idx_ideas_created_at ON ideas(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ideas_is_used ON ideas(is_used);

-- Add comments
COMMENT ON TABLE ideas IS 'Store saved content ideas generated by AI';
COMMENT ON COLUMN ideas.persona IS 'Target persona for the idea';
COMMENT ON COLUMN ideas.industry IS 'Industry/niche for the idea';
COMMENT ON COLUMN ideas.idea IS 'The actual idea content';
COMMENT ON COLUMN ideas.is_used IS 'Whether this idea has been used to create a brief';
